### ISSUE TITLE
[iOS] tr.free-torrents.org - blocked useful elements

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ExperimentalFilter#1181] opened 2015-12-25 12:50 UTC
Не видно объёма раздач:

![image](https://cloud.githubusercontent.com/assets/15856304/12002945/db4b5878-ab16-11e5-9b31-485111401360.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.79 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.50 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.20 Enabled=YES
ID5 Name="RU AdList" Version=1.0.49.48 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.49.44 Enabled=YES

CAA-409-10461

**Comment by Alex-302** [comment] 2015-12-30 10:56
The problem is in RU AdList.
Fixed in our filter.

**Closed by Alex-302** 2015-12-30 10:56 UTC
Labels: iOS
